import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Hanken_Grotesk } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hankenGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0A0A0A] text-white">
        <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden mask-lines">
          <div className="absolute inset-0 flex justify-center">
            <div className="w-full max-w-6xl mx-auto h-full border-x border-white/[0.06]" />
          </div>
          <div className="absolute inset-0 flex justify-center">
            <div className="w-full max-w-4xl mx-auto h-full border-x border-white/[0.03]" />
          </div>
          <div className="absolute inset-0 flex justify-center">
            <div className="w-full max-w-2xl mx-auto h-full border-x border-white/[0.02]" />
          </div>

          <div className="absolute top-0 w-full h-px bg-white/[0.05]" />
          <div className="absolute top-[25%] w-full h-px bg-white/[0.02]" />
          <div className="absolute top-[50%] w-full h-px bg-white/[0.02]" />
          <div className="absolute top-[75%] w-full h-px bg-white/[0.02]" />
          <div className="absolute bottom-0 w-full h-px bg-white/[0.05]" />
        </div>

        <div className="relative z-10 flex flex-col min-h-full">{children}</div>
      </body>
    </html>
  );
}
